Fix tabs/spaces formatting

diff --git a/init-krb b/init-krb
--- a/init-krb
+++ b/init-krb
@@ -42,10 +42,10 @@ while (( $# > 0 )); do
             break
             ;;
         -*)
-			echo "error: unknown option '$opt'"
-			show_help
-			exit 1
-			;;
+            echo "error: unknown option '$opt'"
+            show_help
+            exit 1
+            ;;
         *)
             lifetime=$opt
             shift
diff --git a/jopen b/jopen
--- a/jopen
+++ b/jopen
@@ -41,10 +41,10 @@ while (( $# > 0 )); do
             break
             ;;
         -*)
-			echo "error: unknown option '$opt'"
-			show_help
-			exit 1
-			;;
+            echo "error: unknown option '$opt'"
+            show_help
+            exit 1
+            ;;
         *)
             path_to_open=$opt
             shift
