Clean up input argument parsing and fix typos

diff --git a/init-krb b/init-krb
--- a/init-krb
+++ b/init-krb
@@ -4,42 +4,64 @@
 # =============
 #
 # Initialize a Kerberos ticket and list the currently active tickets.
-# You can also specify the lifetime of the ticket (default is 12h)
+# You can also specify the lifetime of the ticket (default is 12h).
 #
-# Usage
-#
-#   $ init-krb <time>
+# usage: init-krb [--help] [<time>]
 
-# Number of given arguments
-argc=$#
+
+# Script name
+sname=${0##*/}
+
+# Help message
+show_help() {
+cat <<EOF
+usage: ${sname} [--help] [<time>]
+
+Initialize a Kerberos ticket and list the currently active tickets.
+You can also specify the lifetime of the ticket (default is 12h).
+
+optional arguments:
+  <time>       Ticket lifetime, e.g. '24h'; see 'man kinit' for format
+  -h, --help   Show this help message and exit
+EOF
+}
+
+
+# ----- Parse input arguments -----#
+
+while (( $# > 0 )); do
+    opt="$1"
+
+    case $opt in
+        -h|--help)
+            show_help
+            exit 0
+            ;;
+        -*)
+			echo "error: unknown option '$opt'"
+			show_help
+			exit 1
+			;;
+        *)
+            lifetime=$opt
+            shift
+            ;;
+    esac
+done
+
 
 # Get username from scripts repository
 USER="$( cd "$( dirname "${(%):-%N}" )" && cat $(pwd)/.username )"
 
-USAGE="usage: init-krb [--help] <time>"
-
-# Print help message
-if [[ $1 == "--help" ]] && ((argc == 1)); then
-    echo $USAGE
-    exit 0
-fi
-
-# Print help message
-if [[ $1 == "--help" ]] && ((argc > 1)); then
-    echo "init-krb: unrecognized option '${@:2}'"
-    echo $USAGE
-    exit 1
-fi
-
 # Init kerberos ticket with default or specified lifetime
-if ((argc == 0)); then
+if [[ -z $lifetime ]]; then
     kinit -l 12h -f ${USER}@CERN.CH
-elif ((argc == 1)); then
-    kinit -l $1 -f ${USER}@CERN.CH
 else
-    echo $USAGE
-    exit 1
+    kinit -l $lifetime -f ${USER}@CERN.CH
 fi
+
+# Get token for AFS authentication
+aklog
 
 echo
 
diff --git a/lxplus b/lxplus
--- a/lxplus
+++ b/lxplus
@@ -6,6 +6,8 @@
 # Login to CERN's lxplus server. You can login to either the first available
 # node or to a specific node (which is useful if you have a screen session
 # running on that node, as screen sessions cannot be accessed from other nodes).
+#
+# usage: lxplus [--help] [-n|--node <node>] [--no-x11]
 
 
 # Script name
@@ -14,23 +16,22 @@ sname=${0##*/}
 # Help message
 show_help() {
 cat <<EOF
-usage: ${sname} [--help] [--no-x] [NODE]
+usage: ${sname} [--help] [-n|--node <node>] [--no-x11]
 
 Login to CERN's lxplus server. You can login to either the first available
 node or to a specific node (which is useful if you have a screen session
 running on that node, as screen sessions cannot be accessed from other nodes).
 
 optional arguments:
-  --no-x       Disable X11 forwarding (enabled by default)
-  NODE         Login to this lxplus node (e.g. 001, 002, etc.)
+  -n <node>, --node <node>
+               Login to this lxplus node (e.g. 001, 002, etc.)
+  --no-x11     Disable X11 forwarding (enabled by default)
   -h, --help   Show this help message and exit
 EOF
 }
 
 
 # ----- Parse input arguments -----#
-
-POSITIONAL=()  # Array to store positional arguments
 
 USE_X11=true
 
@@ -42,21 +43,22 @@ while (( $# > 0 )); do
             show_help
             exit 0
             ;;
-        --no-x)
+        --no-x11)
             USE_X11=false
             shift
             ;;
-        *)
-            POSITIONAL+=("$1")
+        -n|--node)
+            node="$2"
             shift
+            shift
+            ;;
+        *)
+            echo "error: unknown option '$opt'"
+            show_help
+            exit 1
             ;;
     esac
 done
-
-set -- "${POSITIONAL[@]}"  # Restore positional parameters
-
-# Parse arguments and get arg count
-node=$1
 
 
 # Get username from scripts repository
